name: Backend CI CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '8'
        
    - name: Cache Maven packages
      uses: actions/cache@v2.1.4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
      
    - name: Build with Maven
      run: mvn clean install
      
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'
        
#   deploy-staging:
#     if: github.event_name == 'pull_request' && github.event.action != 'closed'
#     runs-on: windows-latest
#     needs: build
#     environment: 
#       name: 'staging'
#       url: $${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
#     steps:
#     - name: Download artifact from build job
#       uses: actions/download-artifact@v2
#       with:
#         name: java-app
        
#     - name: 'Deploy to Azure Web App'
#       id: deploy-to-webapp
#       uses: azure/webapps-deploy@v2
#       with:
#         app-name: 'horshambags-backend'
#         slot-name: 'staging'
#         publish-profile: ${{ secrets.AZURE_STAGING_PROFILE }}
        
  deploy-to-production:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hclhorshambags-backend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_25C8FF19CF124C17A7CB3300E3ECC9AC }}
          package: '*.jar'
